### PR TITLE
Added docker files

### PR DESCRIPTION
**Pull request by ramschmaerchen**
Allows gitrob usage in a docker environment,
Additional ephemeral postgres container for testing gitrob

### CODE REVIEW

**Comment by michenriksen** [comment]
Hi @ramschmaerchen, thanks for the Pull Request.

Does all these files need to be present in the project itself to work with Docker, or could the Docker setup files reside somewhere else?

**Comment by ramschmaerchen** [comment]
Hej @michenriksen , the only files needed for it to work are those in the docker child-directories. The application itself is installed with bundler.

**Comment by ramschmaerchen** [comment]
We added a new repository. Feel free to clone: https://github.com/aykit/gitrob-docker

**Comment by michenriksen** [comment]
Thanks for your contribution, Other people have also contributed setups for Vagrant and Chef, I will make a section in the README for all these projects.

**Comment by ramschmaerchen** [comment]
Great. I will add docker-compose as soon as it's production ready (aka working on my setup :)

**Pull request closed without merging**
