### PR TITLE
Added Functionality for Continuous Use

### PR DESCRIPTION
**Pull request by tmaudev**
This is a great tool that I've used to help detect possible sensitive information in my organization's repositories. Since we use Gitrob to continuously keep track of our repositories, I added some functionalities that have been useful to us and I thought they would be a good contribution to the project:

1. I added select boxes to the UI that allows users to flag findings based on whether or not they believe there is an actual problem. When the user chooses an option, the 'status' attribute (that I added to the blob model) is updated in the database. Along with this, I added some filters that allow users to choose which findings they want to view in the UI based on the flags. This can help users keep track of the findings, especially if the organization is large.

2. I added an "update" feature that allows an existing organization in the database to be updated. This is useful for users that want to continuously keep track of their organization's repositories. Instead of having to scan the entire organization again (which could take several hours), the update will only scan repositories that have been updated since the last scan. This not only reduces the runtime, but also helps prevent the problem of reaching the Github API rate limit. This update can be done through the UI or the command line.

3. I also implemented support for email notifications. This is useful for users that intend on running Gitrob on a schedule (such as cron jobs) and want to be notified of new or updated repositories and findings. The SMTP settings can be set through the configuration along with which emails the user would like to send the notifications to.

4. I added a delete button to the UI to remove existing scans.

5. I found a bug in one of the error catching statements where it was trying to use a variable that wasn't defined. I fixed this as well.

Thank you,
Tyler

### CODE REVIEW

**Comment by pmotch** [comment]
We would take advantage of this right away! This is great.

**Comment by michenriksen** [comment]
Amazing PR, thank you for contributing this back! :+1: 

I'll have a look at the code later today and merge it back in.

**Comment by tmaudev** [comment]
Hi I was just wondering if you had a chance to look at the code? If you would like me to change anything, I have about 2 weeks before I go on extended leave. I think it would be really cool to see my changes merged in. :) Thanks!

**Comment by mikeatlas** [comment]
:+1: revisit

**Comment by michenriksen** [comment]
Hi @tmaudev, sorry for the long wait, I am taking a break from the Internetz. I gave your fork a test run and it is a great contributation, however I found a couple of minor UI quirks that would be great to have fixed:

UI Quirk 1
The buttons look a bit out of place and seem to have different heights. The Gitrob project uses the [Twitter Bootstrap](http://getbootstrap.com/css/#buttons) project, so it should be an easy fix if you use the button styling from the framework.

UI Quirk 2
It's  a bit hard to read the dropdown box with its current width. I think it would be great to expand it a bit so that it shows the options completely.

The last thing I was thinking about is whether these features should be "unlocked" by a setting? Something a long the lines of "Enable continuous use mode" in the setup wizard. What do you think?

**Comment by tmaudev** [comment]
Those are some great suggestions. When I get the chance, I will make those changes and you can let me know how you like them. Thanks!

**Pull request closed without merging**
